### ISSUE TITLE
The old is the new new - Szymon Kulec

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Devsession-Podcast#10]
W tym odcinku będziemy okrywać na nowo coś co dawno zostało już zdefiniowane :)
Mój gość: [Szymon Kulec](https://blog.scooletz.com)
_Microsoft MVP, architekt, speaker, inżynier oprogramowania oraz współzałożycielem inicjatywy DotNetos.
Z zamiłowaniem łączy architekturę i oprogramowanie wysokiej wydajności. Chętnie dzieli się wiedzą na temat współczesnych architektur, systemów rozproszonych oraz zasad rządzących niskopoziomowym światem niezwykle wydajnych aplikacji. Nigdy nie alokuję przed 12._

**Comment by adbo** [comment]
Co myślisz na temat starego, ale odkrytego na nowo paradygmatu programowania funkcyjnego?

**Comment by Scooletz** [comment]
Czy zamykamy to issue? 😝
