### ISSUE TITLE
Karol Grabowski - od radcy prawnego do programisty

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Devsession-Podcast#2]
## Karol Grabowski
Przez wiele lat radca prawny prowadzący własną kancelarię.
Od ponad roku (?) programista - aktualnie w firmie Nordea.
W tym odcinku omówimy proces zmiany branży przez Karola. Od podjęcia decyzji, przez proces nauki programowania, poszukiwania pierwszej pracy i jej podjęcia.
Wszelkie pytania w tym temacie mile widziane!

**Comment by tom-sapletta-com** [comment]
Jakie mial inspiracje, po co zmienial?
Jak udalo sie podjac pierwsza prace?
Skad bral wiedze, kto mu pomagal w zdobywaniu?
Jakie ma plany na przyszlosc, czy zamierza zmienic kolejny raz, a jesli tak, to na jaka profesje?
Kiedy zamierza przestac byc programista?
Co jest trudne dla niego w IT?
Jak wykorzystuje doswiadczenie radcy w pracy w IT?
Jakie widzi dla siebie miejsce w IT, czy samo programowanie, czy tez prowadzenie projektow, ...?

Czy mozna zobaczyc gdzies kod goscia?

**Comment by Whyshchuck** [comment]
Kilka pytań od programującego po godzinach prawnika:
- czy mimo skupienia swojej codziennej aktywności na programowaniu wciąż wykonuje zawód prawnika - czy całkowicie zrezygnował z dotychczasowej działalności.
- jak wypada porównanie obu zajęć pod względem zaangażowania czasowego, możliwości planowania sobie dnia, tygodnia, miesiąca, roku,
- jak wyglądała jego droga od decyzji do nowej pracy, przez jakie języki rpzehcodził, co go inspirowało, napędzało itd;
- co chciałby robić za 5 lat ;-)
 
Kiedy możemy spodziewać się emisji?

**Comment by GKotfis** [comment]
> Kiedy możemy spodziewać się emisji?

Emisja będzie jeszcze w tym roku! Nie dalej niż za 2 tygodnie.
