### ISSUE TITLE
Tomasz Heimowski - Programowanie Funkcyjne

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Devsession-Podcast#4]
Zapraszam do zadawania pytań! W tym odcinka wypytam [Tomka Heimowskiego](https://twitter.com/theimowski) o co chodzi z tym programowaniem funkcyjnym?!

**Comment by superdurszlak** [comment]
Co ma największy wpływ na wydajność programów pisanych w językach funkcyjnych? Jak implementacje wypadają na tle analogicznych - ale w językach imperatywnych/obiektowych (zakładając jednakowy sposób wykonania programu - np kompilacja do kodu maszynowego lub wykonanie na JVM)? Z punktu widzenia wydajności, na co trzeba najbardziej uważać pracując z językami funkcyjnymi?

**Comment by aixelent** [comment]
Temat "O co chodzi z programowaniem funkcyjnym" więc może pytania nie będą aż tak trywialne lub tendencyjne ale dorzucę coś od siebie.

- Gdybyś miał komuś doradzić jak wejść w programowanie funkcyjne to jak polecałbyś ugryźć temat?
- Jakie Twoim zdaniem są zalety i wady paradygmatu funkcyjnego?
- Jeśli tak to dlaczego polecałbyś pisać funkcyjnie w językach wieloparadygmatowych jak Python czy Go gdy mamy do wyboru (niech będzie to nieszczęsne) OOP.

Podłączam się do pytania @superdurszlak. W świecie języków hybrydowych jaki dziś mamy ciekawi mnie aspekt wydajności. Ten sam kawałek kodu napisany (imperatywnie, obiektowo(przykładowo)) i funkcyjnie.

Jako programista C#/F# (tak mi wyszło z szybkiego researchu) jak postrzegasz zmiany w C#? Mam wrażenie jako obserwator (nie mam już styczności z C#), że dużo przenosi się tam od wersji 6.0 z F#. I, że generalnie C# mocno zmierza w kierunku stania się językiem mocno funkcyjnym.

// Przepraszam za chaos bo to na szybko :smiley:
