### ISSUE TITLE
Katarzyna Gajewska - przyszłość rynku pracy

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Devsession-Podcast#5]
Katarzyna Gajewska, _absolwentka kulturoznawstwa, wiele lat związana z trzecim sektorem, w życiu zawodowym zajmowała się wspieraniem startupów i początkujących przedsiębiorców w PPNT Gdynia, prowadziła też trójmiejski oddział Szkoły Programowania Coders Lab. Koordynatorka spotkań WordCamp Gdynia oraz WordUp Trójmiasto. Prowadzi bloga gajapisze.pl. Pasjonuje ją branża IT, WordPress oraz MCU i Gwiezdne Wojny._
blog: [http://gajapisze.pl](http://gajapisze.pl)

W komentarzach można zadawać pytania związane z temate rozmowy. Czyli dotyczące obecnego rynku pracy, zachodzących zmian, oczekiwań osób wchodzących na rynek pracy itp. itd.

**Comment by GKotfis** [comment]
Od 'Haskell' (4Programmers):
Proszę zapytać Panią Katarzynę, czy uważa, że przekaz marketingowy bootcampów i szkół programowania wprowadza klientów w błąd, co do rzeczywistych warunków i wynagrodzeń w tej branży, szczególnie jeżeli chodzi o stanowiska stażystów i juniorów.

**Comment by pawlos** [comment]
Dla osób, które dopiero wchodzą na rynek pracy w IT lub chcących się przebranżowić (ale w ramach branży) którym trendom warto poświęcić uwagę a które to tylko chwilowa moda?
