### ISSUE TITLE
Michał Michalczuk - przyszłość Frontendu

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Devsession-Podcast#7]
W najbliższym odcinku porozmawiam z @michalczukm o przyszłości Frontendu, nadchodzących nowościach itp.
Jak zawsze możecie dorzucić swoje pytania, problemy w komentarzu :)

**Comment by witek1902** [comment]
Chętnie posłucham nt:
- rozwiązań typu svetle/stencil
- czy nowy, planowany kompilator Angulara (Ivy) jest faktycznie tak rewolucyjny jak się o nim mówi
- czy web components/idea micro frontends to przyszłość
- co z webassembly
- co z Blazorem

**Comment by jotceg** [comment]
Ja od siebie mógłbym dorzucić jeszcze kilka innych tematów:

- PWA, a aplikacje natywne (czy je wyprą, czy warto w nie inwestować, jak Google je wspiera, jak API natywne ma się do tego, co na chwilę obecną już jest w przeglądarce)
- czy React Hooks wyprą pisanie klas,
- W jakim kierunku zmierza JavaScript (nowe wersje ES)
- TypeScript
