### ISSUE TITLE
Konrad Kokosa - O pamięci (tej komputerowej)

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Devsession-Podcast#8]
Konrad Kokosa - [Twitter](https://twitter.com/konradkokosa) | [Blog](http://tooslowexception.com/)
Z Konradem chciałbym poruszyć temat pamięci. Trochę zarys historyczny, jak to się zmieniało w czasie, czasy powstania GC, zarządzanie pamięcią. Odcinek przeprowadzający przez cyfrową rewolucję. Może coś dla fanów mechanical sympathy? Nie będziemy się skupiać tylko na .NET!

**Comment by domer-sz** [comment]
Może jakieś porównanie zarządzania pamięcią przez GC i modelu zarzadzania pamięcią w rust'cie?

**Comment by PiotrKowalski93** [comment]
Co Konrad poleca po przeczytaniu swojej książki? Zostaje praktyka? Kurs? Jak dalej się w tym specjalizować?

**Comment by devmonte** [comment]
Jakie są najczęstsze błędy i złe praktyki związane z pamięcią w C# według Konrada?
