### ISSUE TITLE
O transformacji, zmianie - Katarzyna Michałowska, Marcin Hoppe

### ISSUE THREAD

**Issue by GKotfis** [GKotfis/Devsession-Podcast#9]
Inspiracja do tematu odcinka: https://twitter.com/gkotfis/status/1146321757529432064
W tym odcinku chciałbym poruszyć temat zmiany, pewnej transformacji. Dla przykładu chciałbyś po kilku latach pracy jako backend developer wejść do front'u. Zostać architektem, tech leaderem. A może wykonać zwrot o 180 stopni i wejść do całkiem nieznanej Ci działki jak np. Security?
Do nagrania tego odcinka zaprosiłem dwóch gości: Katarzyne Michałowską ([stacjazmiana.pl](stacjazmiana.pl)) oraz Marcin Hoppe, który nie jako sam się zgłosił :)
Wszelkie pytania do moich rozmówców oraz tematu odcinka wpisujcie w komentarzach!

**Comment by szarotka** [comment]
Cześć Grzesiu! Ostatnio spotkałam się z negatywnymi uwagami wobec kompetencji osób, które pracują dłużej w jednej firmie. Padają argumenty typu: zasiedział się albo przez 4 lata powtarzał rok doświadczenia. Czy ty osobiście spotkałes się z takimi przytykami pod twoim adresem lub podważaniem twoich kompetencji? Czy żałujesz, że decydujesz sie na tę zmianę dopiero teraz?
